test new jenkinsfile

diff --git a/production_app/Jenkinsfile b/production_app/Jenkinsfile
--- a/production_app/Jenkinsfile
+++ b/production_app/Jenkinsfile
@@ -1,5 +1,5 @@
 pipeline {
-    agent {label "build-test-slave-2"}
+    agent { label "build-test-slave-2" }
 
     environment {
         TIME = sh(script: 'date "+%Y-%m-%d %H:%M:%S"', returnStdout: true).trim()
@@ -7,7 +7,6 @@ pipeline {
 
     parameters {
         string(name: 'imagename', defaultValue: '', description: 'Name of the Docker image')
-        string(name: 'imagetag', defaultValue: '', description: 'Image tag for Docker build')
     }
 
     stages {
@@ -19,18 +18,18 @@ pipeline {
                 }
             }
         }
-        stage('Build DockerImage'){
-            steps{
-                echo "build image"
-                dir('/home/ubuntu/workspace/build and test pipeline/MyProject_1/production_app'){
-                sh "docker build -t ${params.imagename}:${params.imagetag} ."
+        stage('Build DockerImage') {
+            steps {
+                echo "Build image"
+                dir('/home/ubuntu/workspace/build and test pipeline/MyProject_1/production_app') {
+                    sh "docker build -t ${params.imagename}:$BUILD_NUMBER ."
                 }
             }
         }
-        stage('Run Container'){
-            steps{
-                sh "docker run -it --name flask-app -p 5000:5000 -d ${params.imagename}:${params.imagetag}"
-                }
+        stage('Run Container') {
+            steps {
+                sh "docker run -it --name flask-app -p 5000:5000 -d ${params.imagename}:$BUILD_NUMBER"
+            }
         }
         stage("build user") {
             steps {
@@ -42,49 +41,60 @@ pipeline {
         }
         stage('test application') {
             steps {
-                echo "test"
-                dir('/home/ubuntu/workspace/build and test pipeline/MyProject_1/production_app/'){
-                sh 'pytest tests.py::Test_class::test_signup --html=test_report.html'
+                echo "Test"
+                dir('/home/ubuntu/workspace/build and test pipeline/MyProject_1/production_app') {
+                    sh 'pytest tests.py::Test_class::test_signup --html=test_report.html'
+                }
+            }
+            post {
+                always {
+                    script {
+                        def testResult = sh(script: 'cat test_report.html | grep "FAIL" || true', returnStatus: true)
+                        if (testResult == 0) {
+                            error("Tests failed. Aborting the pipeline.")
+                        }
+                    }
                 }
             }
         }
-        stage ('upload to s3 bucket'){
+        stage('Upload to S3 bucket') {
             steps {
                 withAWS(credentials: 'AWScredentials') {
                     sh '/root/.local/bin/aws s3 cp "/home/ubuntu/workspace/build and test pipeline/MyProject_1/production_app/test_report.html" "s3://project1-results"'
                 }
             }
         }
-        stage('UploadToDynamoDB') {
-            steps {       
-            dir('/home/ubuntu/workspace/build and test pipeline/MyProject_1/production_app') {
-                script {
-                    def log_entry = sh(script: 'python3.8 logfile.py', returnStdout: true).trim()
-                    def (timestamp, message) = log_entry.split(',')
-                    message = message.replaceAll('"', '\\"') // add this line to escape quotation marks
-                    withAWS(credentials: 'AWScredentials', region: 'us-west-2') {
-                    sh "/root/.local/bin/aws dynamodb put-item --table-name project_build_report --item \"{\\\"user\\\": {\\\"S\\\": \\\"${env.BUILD_USER}\\\"}, \\\"date\\\": {\\\"S\\\": \\\"${timestamp}\\\"}, \\\"result\\\": {\\\"S\\\": \\\"${message}\\\"}}\""
+        stage('Upload to DynamoDB') {
+            steps {
+                dir('/home/ubuntu/workspace/build and test pipeline/MyProject_1/production_app') {
+                    script {
+                        def log_entry = sh(script: 'python3.8 logfile.py', returnStdout: true).trim()
+                        def (timestamp, message) = log_entry.split(',')
+                        message = message.replaceAll('"', '\\"') // add this line to escape quotation marks
+                        withAWS(credentials: 'AWScredentials', region: 'us-west-2') {
+                            sh "/root/.local/bin/aws dynamodb put-item --table-name project_build_report --item \"{\\\"user\\\": {\\\"S\\\": \\\"${env.BUILD_USER}\\\"}, \\\"date\\\": {\\\"S\\\": \\\"${timestamp}\\\"}, \\\"result\\\": {\\\"S\\\": \\\"${message}\\\"}}\""
+                        }
                     }
                 }
             }
-            }
         }
         stage('UploadImageToDockerHub') {
-        steps {
-            script {
-                def dockerImageName = "${params.imagename}:${params.imagetag}"
-                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_HUB_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
-                    sh "docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_PASSWORD"
-                    echo "login"
-                    sh "docker tag ${dockerImageName} puki121/project:${params.imagetag}"
-                    sh "docker push puki121/project:${params.imagetag}"
-                    build job: 'deployment', parameters: [
-                    // string(name: 'imagename', value: params.imagename),
-                    string(name: 'imagetag', value: params.imagetag)]                
+            steps {
+                script {
+                    def dockerImageName = "${params.imagename}"
+                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_HUB_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
+                        sh "docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_PASSWORD"
+                        echo "Login"
+                        def dockerHubImageName = "puki121/project:$BUILD_NUMBER"
+                        sh "docker tag ${dockerImageName} ${dockerHubImageName}"
+                        sh "docker push ${dockerHubImageName}"
+                        build job: 'deployment', parameters: [
+                            string(name: 'imagename', value: dockerImageName),
+                            string(name: 'imagetag', value: BUILD_NUMBER)
+                        ]
                     }
+                }
             }
-        }
         }
     }
 }
-
